micronaut:
  application:
    name: retroboard

  server:
    host: localhost
    port: 8080

  router:
    static-resources:
      default:
        enabled: true
        mapping: "/static/**"
        paths: classpath:public

  session:
    http:
#      cookie: false
#      header: true
      redis:
        enabled: true
        server-name: default

  views:
    pebble:
      enabled: true
      default-extension: peb

redis:
  servers:
    default:
      host: localhost
      port: 6379
      password: str0ng_passw0rd
    pub:
      host: localhost
      port: 6379
      password: str0ng_passw0rd

netty:
  default:
    allocator:
      max-order: 3
