micronaut:
  executors:
    scheduled:
      type: scheduled
      core-pool-size: 10

  application:
    name: retroboard

  server:
    host: 0.0.0.0
    port: 8080
    idle-timeout: 10m
    read-idle-timeout: 10m
    write-idle-timeout: 10m

  router:
    static-resources:
      default:
        enabled: true
        mapping: "/static/**"
        paths: classpath:public

  session:
    http:
#      cookie: false
#      header: true
      redis:
        enabled: true
        server-name: default

  views:
    pebble:
      enabled: true
      default-extension: peb

retroboard:
  domain: "${RETROBOARD_DOMAIN:localhost}"

redis:
    servers:
      default:
        host: "${REDIS_DEFAULT_HOST:localhost}"
        port: ${REDIS_DEFAULT_PORT:6379}
        password: str0ng_passw0rd
      pub:
        host: "${REDIS_DEFAULT_HOST:localhost}"
        port: ${REDIS_DEFAULT_PORT:6379}
        password: str0ng_passw0rd
      sub:
        host: "${REDIS_SUB_HOST:localhost}"
        port: ${REDIS_SUB_PORT:6380}
        password: str0ng_passw0rd

netty:
  default:
    allocator:
      max-order: 3
